variable "is_enabled" {}
variable "function" {}
variable "lambda_function_name" {}
variable "lambdafile_count" {}
variable "code-for-lambda" {}
variable "runtime-for-lambda" {}
variable "handler-for-lambda" {}
variable "role-for-lambda" {}
variable "timeout-for-lambda" {}
variable "memory-size-for-lambda" {}
variable "lambda_env" {}