properties([parameters([choice(choices: ['Lambda-Function', 'Cloudwatch-Monitoring', 'IAM-Roles', 'EC2-Instance', 'S3-Bucket', 'Glue-Jobs', 'DynamoDB', 'SNS-Topic', 'VPC-Networking'], name: 'Module_Name'), string(defaultValue: 'dev.tfvars', name: 'File_Name'), string(defaultValue: 'Terraform-Module-Deployment', name: 'Pipeline')])])
pipeline {
    agent any
    stages {
        stage('Preparing') {
            steps {
                sh 'echo Preparing'
            }
        }
        stage('Git Pulling') {
            steps {
                git branch: 'Modularized-Terraform', url: 'https://github.com/AmanPathak-dev/Terraform.git'
                sh 'ls'
            }
        }
        stage('Terraform Init') {
            steps {
                echo "Enter File Name ${params.Module_Name}"
                echo "Pipeline Name ${params.Pipeline}"
                sh 'terraform -chdir=/var/lib/jenkins/workspace/${Pipeline}/Modularized/Terraform-Modularized/${Module_Name}/ init'
            }
        }
        stage('Terraform Plan') {
            steps {
                sh 'ls'
                // sh 'cp Modularized/Terraform-Modularized/variables.tf ${Module_Name}/'
                sh 'cp /var/lib/jenkins/workspace/${Pipeline}/Modularized/Terraform-Modularized/variables.tf /var/lib/jenkins/workspace/${Pipeline}/Modularized/Terraform-Modularized/${Module_Name}/'
                sh 'cd Modularized/Terraform-Modularized/${Module_Name}/'
                withAWS(credentials: 'jenkins-environment', region: 'us-east-1') {
                echo "Enter File Name ${params.File_Name}"  
                sh 'terraform get -update'  
                sh 'terraform -chdir=/var/lib/jenkins/workspace/${Pipeline}/Modularized/Terraform-Modularized/${Module_Name}/ plan -var-file=/var/lib/jenkins/workspace/${Pipeline}/Modularized/Terraform-Modularized/${File_Name}'
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                sh 'ls'
                sh 'cp /var/lib/jenkins/workspace/${Pipeline}/Modularized/Terraform-Modularized/variables.tf /var/lib/jenkins/workspace/${Pipeline}/Modularized/Terraform-Modularized/${Module_Name}/'
                // sh 'cp Modularized/Terraform-Modularized/variables.tf ${Module_Name}/'
                sh 'cd Modularized/Terraform-Modularized/${Module_Name}/'
                withAWS(credentials: 'jenkins-environment', region: 'us-east-1') {
                sh 'terraform get -update' 
                sh 'terraform -chdir=/var/lib/jenkins/workspace/${Pipeline}/Modularized/Terraform-Modularized/${Module_Name}/ apply -auto-approve -var-file=/var/lib/jenkins/workspace/${Pipeline}/Modularized/Terraform-Modularized/${File_Name}'
                }
            }
        }
    }
}